import { Router } from 'express';
import { listWorkOrders, getWorkOrder, createWorkOrder, updateWorkOrder, deleteWorkOrder } from './workOrders.controller';
import { authenticate } from '../../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/',     listWorkOrders);
router.post('/',    createWorkOrder);
router.get('/:id',  getWorkOrder);
router.put('/:id',  updateWorkOrder);
router.delete('/:id', deleteWorkOrder);
export default router;
