/**
 * Writes src/theme.css: every palette the app uses, as CSS variables, once
 * for light and once for dark.
 *
 * The app has some two thousand colour classes (text-stone-700, bg-red-50 and
 * the like). Giving each a dark: twin would double that and drift the first
 * time someone forgets one. Instead the palettes themselves are variables,
 * tailwind.config.js points every class at them, and dark mode swaps the
 * values. A class written today is dark-mode correct without anyone thinking
 * about it.
 *
 * Run: node scripts/gen-theme.cjs   (re-run if a palette is added)
 */
const fs = require('fs');
const path = require('path');
const tw = require('tailwindcss/colors');
const cfg = require('../tailwind.palettes.cjs');

const SHADES = ['50','100','200','300','400','500','600','700','800','900','950'];
const rgb = hex => {
  const h = hex.replace('#', '');
  const n = parseInt(h.length === 3 ? h.split('').map(c => c + c).join('') : h, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
};

/*
 * Stone is the neutral everything sits on, so it is chosen rather than
 * inverted: a straight flip makes stone-50 near-black and stone-900 white,
 * which is right in direction but harsh at both ends. These keep the warm bias
 * of the light theme (the brand is ochre) and leave real room between the
 * ground, a card, a border and muted text.
 */
const STONE_DARK = {
  50:  '#221e1b', 100: '#29241f', 200: '#3a342e', 300: '#524b44',
  400: '#968f88', 500: '#aea79f', 600: '#beb7b0', 700: '#d6d1cb',
  800: '#e8e4df', 900: '#f4f1ed', 950: '#faf8f5',
};

const palettes = { ...cfg.custom };
for (const name of cfg.tailwind) palettes[name] = tw[name];

const light = [], dark = [];
for (const [name, scale] of Object.entries(palettes)) {
  for (const s of SHADES) {
    if (!scale[s]) continue;
    light.push(`  --c-${name}-${s}: ${rgb(scale[s])};`);
    // Everything except stone mirrors around 500: a pale tint used as a
    // background becomes a deep one, and the dark shade used for its text
    // becomes a light one, so each pairing keeps its contrast.
    const mirror = SHADES[SHADES.length - 1 - SHADES.indexOf(s)];
    const value = name === 'stone' ? STONE_DARK[s] : (scale[mirror] ?? scale[s]);
    dark.push(`  --c-${name}-${s}: ${rgb(value)};`);
  }
}

const css = `/* Generated by scripts/gen-theme.cjs. Edit that, not this. */

:root {
  color-scheme: light;
  --c-white: 255 255 255;
  /* The soft-UI surfaces: the page ground and the two shadows that raise or
     sink an element on it. */
  --ground: 232 235 240;
  --neu-dark: 197 202 211;
  --neu-light: 255 255 255;
  /* The dark "ink" fill of primary buttons, and the cool grey of table rules. */
  --ink-from: 67 67 67;
  --ink-to: 26 26 26;
  --line: 163 177 198;
  /* The warm paper behind sign-in, sign-up and setup. */
  --paper: 248 245 240;
${light.join('\n')}
}

.dark {
  color-scheme: dark;
  /* "White" is a surface far more often than it is ink, so it becomes the
     card colour. Where it was ink on a coloured fill, the fill has flipped
     lighter at the same time, so the pairing still reads. */
  --c-white: 30 27 24;
  --ground: 21 18 15;
  --neu-dark: 9 8 7;
  --neu-light: 38 33 29;
  /* Primary buttons turn light: their label is text-white, which is now the
     dark card colour, so a dark fill would swallow it. */
  --ink-from: 244 241 237;
  --ink-to: 214 209 203;
  --line: 82 75 68;
  --paper: 21 18 15;
${dark.join('\n')}
}

/* Paper is white. Whatever the screen is showing, anything printed (a
   receipt, an invoice, a report) uses the light values, so nobody burns a
   cartridge on a dark background or hands a customer an unreadable slip. */
@media print {
  .dark {
    color-scheme: light;
    --c-white: 255 255 255;
    --ground: 255 255 255;
    --neu-dark: 197 202 211;
    --neu-light: 255 255 255;
    --ink-from: 67 67 67;
    --ink-to: 26 26 26;
    --line: 163 177 198;
    --paper: 255 255 255;
${light.join('\n').replace(/^  /gm, '    ')}
  }
}
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'theme.css'), css);
console.log(`wrote src/theme.css: ${Object.keys(palettes).length} palettes, ${light.length} shades`);
