ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "tin" TEXT;
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "vrn" TEXT;

ALTER TABLE "shops" ALTER COLUMN "country" SET DEFAULT 'TZ';
ALTER TABLE "shops" ALTER COLUMN "timezone" SET DEFAULT 'Africa/Dar_es_Salaam';
ALTER TABLE "shops" ALTER COLUMN "currency" SET DEFAULT 'TZS';
