import { Router } from 'express';
import { listRooms, createRoom, updateRoom, deleteRoom, listFolios, checkIn, getFolio, addCharge, checkOut, settleFolio, listDebts } from './hotel.controller';
import { authenticate } from '../../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/rooms',                      listRooms);
router.post('/rooms',                     createRoom);
router.put('/rooms/:id',                  updateRoom);
router.delete('/rooms/:id',               deleteRoom);
router.get('/folios',                     listFolios);
router.get('/folios/debts',               listDebts);
router.post('/check-in',                  checkIn);
router.get('/folios/:id',                 getFolio);
router.post('/folios/:id/charges',        addCharge);
router.post('/folios/:id/check-out',      checkOut);
router.post('/folios/:id/settle',         settleFolio);
export default router;
