import palettes from './tailwind.palettes.cjs';

const SHADES = ['50','100','200','300','400','500','600','700','800','900','950'];
const names = [...palettes.tailwind, ...Object.keys(palettes.custom)];
const themed = Object.fromEntries(names.map(name => [
  name,
  Object.fromEntries(SHADES.map(s => [s, `rgb(var(--c-${name}-${s}) / <alpha-value>)`])),
]));

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      // Every palette below reads a CSS variable, set for light in :root and
      // for dark under .dark (src/theme.css, generated by scripts/gen-theme).
      // Classes stay exactly as written; the theme is a change of values.
      colors: {
        ...themed,
        white: 'rgb(var(--c-white) / <alpha-value>)',
        // White that stays white. "white" above is a surface and follows the
        // theme; this is for ink on a fill that does not change, such as the
        // dark splash, a photo, or a brand-coloured button.
        snow: '#ffffff',
        accent: { 400: '#c4a882', 500: '#a88a62' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      letterSpacing: { widest: '0.15em' },
      animation: { 'scan-line': 'scanLine 2s ease-in-out infinite' },
      keyframes: { scanLine: { '0%, 100%': { top: '0%', opacity: '1' }, '50%': { top: '100%', opacity: '0.7' } } },
    },
  },
  plugins: [],
};
